services:
  app:
    build: .
    ports:
      - "3000:3000"
    # This loads the .env file into the container at runtime
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ojqntdmhoq
      - POSTGRES_DB=docker-postgres-pms
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: